exports.handler = async (event, context) => {
  const items = [
    "a cedar sprig.",
    "a wild dandelion.",
    "someone's berry stash.",
    "a pinecone charm.",
    "a giant chanterelle.",
    "a glowing shroom.",
    "a perfectly smooth stone.",
    "a tiny marimo ball.",
    "a jar of rainwater.",
    "a curled fern frond.",
    "a bundle of sage.",
    "a bit of honeycomb.",
    "a wild morel.",
    "a crocheted acorn.",
    "a partially melted candle.",
    "a mossy log.",
    "a handful of soil.",
    "a seed shaped like a heart.",
    "a single blueberry.",
    "a small spiraling snail shell.",
    "a piece of snake shed.",
    "a robin's eggshell.",
    "a rusted crochet hook.",
    "a four-leaf clover.",
    "a soft patch of mint.",
    "a fairy door. You catch a shining orb floating out.",
    "a crown of pine needles.",
    "a bit of lichen.",
    "a painting of a mushroom.",
    "a jar of fireflies.",
    "a mysterious lantern.",
    "a sprig of rosemary.",
    "a small creature hiding under a wildflower.",
    "a forest fairy.",
    "a bundle of herbs.",
    "a cluster of oyster shrooms.",
    "a small moss terrarium.",
    "a leaf shaped like a star.",
    "a cracked walnut.",
    "an unsuspecting sprout.",
    "a bed of moss.",
    "a soil sprite.",
    "a scrap of weathered parchment.",
    "a fluff of cattail.",
    "a garden gnome.",
    "a fairy ring made of puffballs.",
    "a nest of woven grasses.",
    "a field of forest flowers tucked behind a curtain of moss.",
    "something special. The trickle of water beckons you closer; beneath the ripples of a stream, a glowing fish rises to greet you.",
    "a secret. The moss grows brighter here, and a small shroom sprite shyly approaches."
  ];

  const actions = [
    "hums softly in thanks.",
    "smells faintly of rain.",
    "shimmers for a moment.",
    "sighs softly, then settles peacefully.",
    "makes the moss brighter.",
    "surrounds you with warmth.",
    "catches the interest of a small bird nearby.",
    "sinks into the soil.",
    "is tangled in roots; you let it stay there.",
    "shines through the fog.",
    "shakes the ground; a few leaves fall from the trees.",
    "is delicate; you let it rest.",
    "glistens with dew.",
    "carries a feeling of calm.",
    "catches the morning light just right.",
    "tumbles away playfully.",
    "glows faintly, but maybe it's a reflection.",
    "has a tiny mushroom growing from it.",
    "makes the wind whistle a familiar tune.",
    "is heavier than it looks.",
    "is slick with fresh rainwater.",
    "fits perfectly in your satchel; you begin your adventure together.",
    "shows appreciation for your gentle handling.",
    "leaves you with a sense of whimsy.",
    "squelches softly when you squeeze it.",
    "asks you to take it along on your journey.",
    "attracts a curious green beetle.",
    "gives you a feeling of nostalgia.",
    "pulls you toward a patch of sunlight.",
    "smells slightly of black tea.",
    "looks like the animals were intrigued by it too.",
    "makes your stomach rumble; you crave soup.",
    "looks like something you'd see in a dream.",
    "leaves a faint glowing smear on everything it touches.",
    "feels like the warmth from a fire.",
    "helps you feel less alone.",
    "seems like it's been here for decades.",
    "feels as if you're the first human to lay eyes on it.",
    "warms you with a sense of ease.",
    "wishes you well on your travels; you swell with happiness.",
    "draws your attention to a trail of animal tracks.",
    "seems like it was left here just for you to find.",
    "looks ordinary—until it isn't.",
    "sets a chill to the air; you shiver.",
    "entices you to sit and enjoy the view.",
    "seems to rumble with quiet energy.",
    "reminds you of Mossy. ♡",
    "whispers with the wind: \"Keep going.\"",
    "yearns to be held closer.",
    "allows you to reach for it, and the sky turns sunny when you finally touch it."
  ];

  // Random selection
  const randomItem = items[Math.floor(Math.random() * items.length)];
  const randomAction = actions[Math.floor(Math.random() * actions.length)];

  const response = `You have found ${randomItem} It ${randomAction}`;

  return {
    statusCode: 200,
    body: response
  };
};
